DROP TABLE IF EXISTS BBS_Post_Test;
CREATE TABLE BBS_Post_Test(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
  title VARCHAR(100) NOT NULL
);
INSERT INTO  BBS_Post(title) VALUES ("Title 1");
INSERT INTO  BBS_Post(title) VALUES ("Title 2")
