DROP TABLE IF EXISTS BBS_Post;
CREATE TABLE BBS_Post(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
  title VARCHAR(100) NOT NULL
);
INSERT INTO  BBS_Post(title) VALUES ("Title 1");
INSERT INTO  BBS_Post(title) VALUES ("Title 2")